[project]
name = "multi-agent-langgraph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-ollama",
    "langchain-core",
    "pydantic",
    "mcp",
    "langgraph>=0.6.7",
    "requests>=2.32.5",
]

